name: Build PocketDrop Installer

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-package:
    runs-on: windows-latest
    
    # THE MATRIX: This tells GitHub to run this entire job 3 separate times simultaneously!
    strategy:
      matrix:
        target: [win-x64, win-x86, win-arm64]
        include:
          - target: win-x64
            arch: x64
          - target: win-x86
            arch: x86
          - target: win-arm64
            arch: arm64

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # The -r flag now dynamically pulls from the matrix (win-x64, win-x86, win-arm64)
    - name: Publish PocketDrop
      run: dotnet publish ./PocketDrop/PocketDrop.csproj -c Release -r ${{ matrix.target }} --self-contained false -o ./publish

    # We call the native Inno Setup compiler and inject the /D flag to set our variable
    - name: Compile Inno Setup
      run: iscc /DMyAppArch="${{ matrix.arch }}" ./Setup.iss

    # Uploads 3 separate zip folders to your Actions page!
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PocketDrop_Installer-${{ matrix.arch }}
        path: Output/*.exe